# Site settings
name: Angeline Neo
title: Angeline Neoo | UI/UX designer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://angelineneo.me/
baseurl: ''
email: anpy.angeline@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://github.com/Angelineo/angelineo.github.io/blob/master/resume.pdf
social:
  - title: email
    url: anpy.angeline@gmail.com
  - title: twitter
    url: https://twitter.com/bchiang7
  - title: instagram
    url: https://instagram.com/bchiang7
  - title: codepen
    url: http://codepen.io/bchiang7
  - title: github
    url: https://github.com/Angelineo/angelineo.github.io
  - title: linkedin
    url: https://www.linkedin.com/in/angeline-neo/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
